version: '3'
services:
      web:
          build: .
          ports:
            - "5000:5000"
          networks:
            - counter-net
      redis:
          image: "redis:alpine"
          networks:
            - counter-net
networks:
      counter-net:
